### ISSUE TITLE
Download mojmap do not follow installer's --offline and --debug option

### ISSUE THREAD

**Issue by IzzelAliz** [MinecraftForge/InstallerTools#13]

**Comment by LexManos** [comment]
So the problem, is Mojang can change the hash of these files at any time so we cant use output hashing the cache this task.
And moving it to the installer is a breaking change adding more special cases into the installer, which defeats the point of the new installer format.
As it sits, Forge's installers can't be run in --offline mode because it needs to download Minecraft, Forge, All our libraries, etc...
So.... What's the point? Perhaps we could add a mode that tells it to trust the cache. But that wouldn't be triggered by any flags from the installer. You'd have to ask specifically.

**Comment by IzzelAliz** [comment]
Yes, adding a mode that trust the cache can solve this.

In previous versions if I want to upgrade a server behind firewalls, the installer can be run offline when upgrading patch versions without library changes, but now it just fails.
